keycloak:
  name: keycloak

realm:
  name: backstage

hook:
  image:
    repository: quay.io/cloud-architecture-workshop/wait-for-statefulset-job
    pullPolicy: IfNotPresent
    tag: "1c68180"
  serviceAccount:
    create: true
    name: ""
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  maxTimeToWait: 120000

users:
  count: 5
  prefix: user
  password:

argocd:
  enabled: true
  syncwave: "-1"

