nameOverride: "noobaa"
fullnameOverride: ""

namespace: ""

noobaa:
  subscription:
    channel: stable-4.16
    installPlanApproval: Automatic
    name: mcg-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace

argocd:
  enabled: true
  operatorgroup:
    syncwave: "-3"
  operator:
    syncwave: "-2"
